package windowLogIn;

import controladores.ControladorDueloEntreLeyendas;

@SuppressWarnings("all")
public class WindowLogIn /* implements MainWindow<ControladorDueloEntreLeyendas>  */{
  public WindowLogIn(final ControladorDueloEntreLeyendas model) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super is undefined for the type WindowLogIn");
  }
  
  public Object createContents(final /* Panel */Object panel) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method setTitle is undefined for the type WindowLogIn"
      + "\nVerticalLayout cannot be resolved."
      + "\nLabel cannot be resolved."
      + "\nThe method setText is undefined for the type WindowLogIn"
      + "\nThe method or field fontSize is undefined for the type WindowLogIn"
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nThe method or field height is undefined for the type WindowLogIn"
      + "\nPanel cannot be resolved."
      + "\nHorizontalLayout cannot be resolved."
      + "\nLabel cannot be resolved."
      + "\nThe method setText is undefined for the type WindowLogIn"
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nTextBox cannot be resolved."
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nThe method bindValueToProperty is undefined for the type WindowLogIn"
      + "\nPanel cannot be resolved."
      + "\nHorizontalLayout cannot be resolved."
      + "\nLabel cannot be resolved."
      + "\nThe method setText is undefined for the type WindowLogIn"
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nTextBox cannot be resolved."
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nThe method bindValueToProperty is undefined for the type WindowLogIn"
      + "\nLabel cannot be resolved."
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nThe method or field foreground is undefined for the type WindowLogIn"
      + "\nThe method bindValueToProperty is undefined for the type WindowLogIn"
      + "\nPanel cannot be resolved."
      + "\nHorizontalLayout cannot be resolved."
      + "\nColumnLayout cannot be resolved."
      + "\nButton cannot be resolved."
      + "\nThe method or field caption is undefined for the type WindowLogIn"
      + "\nThe method onClick is undefined for the type WindowLogIn"
      + "\nThe method or field width is undefined for the type WindowLogIn"
      + "\nButton cannot be resolved."
      + "\nThe method or field caption is undefined for the type WindowLogIn"
      + "\nThe method onClick is undefined for the type WindowLogIn"
      + "\nsetLayout cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nsetLayout cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nsetLayout cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nsetLayout cannot be resolved"
      + "\nlayout cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved");
  }
  
  public Object loguearUsuario() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field modelObject is undefined for the type WindowLogIn"
      + "\nThe method or field modelObject is undefined for the type WindowLogIn"
      + "\npuedoLoguear cannot be resolved"
      + "\nloguear cannot be resolved");
  }
  
  public Object openDialog(final /* Dialog<?> */Object dialog) {
    throw new Error("Unresolved compilation problems:"
      + "\nopen cannot be resolved");
  }
  
  public Object registrarUsuario() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field modelObject is undefined for the type WindowLogIn"
      + "\nregistrarUsuario cannot be resolved");
  }
  
  public static Object main(final String[] args) {
    throw new Error("Unresolved compilation problems:"
      + "\nDueloEntreLeyendas cannot be resolved."
      + "\nUsuario cannot be resolved."
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type WindowLogIn"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type WindowLogIn"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type WindowLogIn"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type WindowLogIn"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type WindowLogIn"
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nUsuario cannot be resolved."
      + "\nUsuario cannot be resolved."
      + "\nTarjetaDeDuelo cannot be resolved."
      + "\nThe method or field Linea is undefined for the type WindowLogIn"
      + "\nTarjetaDeDuelo cannot be resolved."
      + "\nThe method or field Linea is undefined for the type WindowLogIn"
      + "\nThe method startApplication is undefined for the type WindowLogIn"
      + "\nBottom cannot be resolved"
      + "\nJungle cannot be resolved"
      + "\nMid cannot be resolved"
      + "\nMid cannot be resolved"
      + "\nTop cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nusuarios cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nBottom cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nMid cannot be resolved"
      + "\nbuscadores cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nbuscadores cannot be resolved"
      + "\nadd cannot be resolved");
  }
}
