package aplicacion;

@SuppressWarnings("all")
public class AplicacionDueloEntreLeyendas {
  public static Object main(final String[] args) {
    throw new Error("Unresolved compilation problems:"
      + "\nDueloEntreLeyendas cannot be resolved."
      + "\nUsuario cannot be resolved."
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nPersonaje cannot be resolved."
      + "\nThe method or field Linea is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nEstadisticas cannot be resolved."
      + "\nUsuario cannot be resolved."
      + "\nUsuario cannot be resolved."
      + "\nTarjetaDeDuelo cannot be resolved."
      + "\nThe method or field Linea is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nTarjetaDeDuelo cannot be resolved."
      + "\nThe method or field Linea is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nThe method startApplication is undefined for the type AplicacionDueloEntreLeyendas"
      + "\nBottom cannot be resolved"
      + "\nJungle cannot be resolved"
      + "\nMid cannot be resolved"
      + "\nMid cannot be resolved"
      + "\nTop cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\npersonajes cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nusuarios cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nestadisticas cannot be resolved"
      + "\nadd cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nBottom cannot be resolved"
      + "\njugador cannot be resolved"
      + "\nMid cannot be resolved"
      + "\nbuscadores cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nbuscadores cannot be resolved"
      + "\nadd cannot be resolved");
  }
}
